spring:
  thymeleaf:
    cache: false

#server:
#  port: 8443
#  ssl:
#    key-store: file:///Users/mousesd/Documents/Spring/SpringBootInAction/Lib/springboot.jks
#    key-store-password: letmein
#    key-password: letmein

#logging:
#  level:
#    root: warn
#    org.springframework.security: debug

amazon:
  associatedId: habuma-20
